### ISSUE TITLE
django-parler and page

### ISSUE THREAD

**Issue by weber-s** [webu/wagtail-parler#3]
django-parler define a useful templatetag `get_translated_url` allowing language switch. For instance:

```htmldjango
{% for language in languages %}
    {% get_translated_url language.code as tr_url %}
    <a href="{{ tr_url }}">
        <span class="btn {% if language.code == request.LANGUAGE_CODE %}active{% endif %}">{{ language.code|upper }}</span>
    </a>
{% endfor %}
```

however the internal of `get_translated_url` try to guess the current page (using potentially some hacky stuff, that works also for wagtail), and return `get_absolute_url()` of the best object found.

And here is the bug: wagtail `Page` object does not define a `get_absolute_url` but a `get_url`. So something like

```py
def get_absolute_url(self):
    return self.localized.get_url()
```
in the `Page` model fix it.

Question: should it be in wagtail-parler, django-parler or wagtail ?

**Comment by DylannCordel** [comment]
As you say, django-parler try to guess current object displayed via the context or the view. If you want it works with wagtail page, you must add get_absolute_url to Page model and Snippet you use.

This is not really clean but this will work:

```python
from django.apps import AppConfig
from django.utils.translation import gettext_lazy as _


class MyAppConfig(AppConfig):
    name = "my_app

    def ready(self):
        from wagtail.models import Page
        def get_absolute_url(self, *args, **kwargs):
            return self.get_url(request=kwargs.get("request", None))
        Page.get_absolute_url = get_absolute_url
```
